# Generated by Django 5.0.14 on 2026-08-06 07:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TechStack',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('category', models.CharField(help_text='E.g: Frontend, Backend, Database', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioProject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(help_text='Used for clean URLs', max_length=120, unique=True)),
                ('description', models.TextField()),
                ('github_url', models.URLField(blank=True, null=True)),
                ('swagger_url', models.URLField(blank=True, null=True)),
                ('architecture_url', models.URLField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tech_stacks', models.ManyToManyField(related_name='projects', to='api.techstack')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
