# Generated by Django 5.0.8 on 2026-08-19 06:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiPlaygroundLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('endpoint', models.CharField(default='/api/v1/playground/echo/', max_length=100)),
                ('method', models.CharField(default='POST', max_length=10)),
                ('latency_ms', models.IntegerField(help_text='Response time in milliseconds')),
                ('response_status', models.IntegerField(default=200)),
                ('ip_hash', models.CharField(max_length=256)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
